let value="0";
let decimalPointFlag=true;
let CalculationFlag=false;
let operatorZeroFlag=false;
let equalFlag=true;

function safeEval(val){
    return Function('"use strict";return ('+val+')')();
}

$(document).ready(function(){
    $("#one,#two,#three,#four,#Five,#Six,#Seven,#Eight,#Nine").click(function(){
        if(value=="0"){
            value=$(this).html();
        }else{
            value+=$(this).html();
        }
        $("#zero").attr("disabled",false);
        $("#doubleZero").attr("disabled",false);
        $("#plus").attr("disabled",false);
        $("#minus").attr("disabled",false);
        $("#multiply").attr("disabled",false);
        $("#divide").attr("disabled",false);
        operatorZeroFlag=false;
        if(decimalPointFlag){
            $("#decimalPoint").attr("disabled",false);
        }
        if(CalculationFlag){
            $("#equal").attr("disabled",false);
        }
        $("h1").text(value);
    });
    
    $("#plus,#minus,#multiply,#divide").click(function(){
        if(value=="0"&&equalFlag){
            value=$(this).html();
        }else{
            value+=$(this).html();
        }
        decimalPointFlag=true;
        if(value!="-"){
            CalculationFlag=true;
        }
        operatorZeroFlag=true;
        $("#doubleZero").attr("disabled",true);
        $("#plus").attr("disabled",true);
        $("#minus").attr("disabled",true);
        $("#multiply").attr("disabled",true);
        $("#divide").attr("disabled",true);
        $("#decimalPoint").attr("disabled",true);
        $("#equal").attr("disabled",true);
        $("#zero").attr("disabled",false);
        $("#one").attr("disabled",false);
        $("#two").attr("disabled",false);
        $("#three").attr("disabled",false);
        $("#four").attr("disabled",false);
        $("#Five").attr("disabled",false);
        $("#Six").attr("disabled",false);
        $("#Seven").attr("disabled",false);
        $("#Eight").attr("disabled",false);
        $("#Nine").attr("disabled",false);
        $("h1").text(value);
    });
    
    $("#zero,#doubleZero").click(function(){
        value+=$(this).html();
        if(decimalPointFlag){
            $("#decimalPoint").attr("disabled",false);
            $("#zero").attr("disabled",false);
            $("#one").attr("disabled",false);
            $("#two").attr("disabled",false);
            $("#three").attr("disabled",false);
            $("#four").attr("disabled",false);
            $("#Five").attr("disabled",false);
            $("#Six").attr("disabled",false);
            $("#Seven").attr("disabled",false);
            $("#Eight").attr("disabled",false);
            $("#Nine").attr("disabled",false);
        }
        if(!decimalPointFlag){
            $("#plus").attr("disabled",true);
            $("#minus").attr("disabled",true);
            $("#multiply").attr("disabled",true);
            $("#divide").attr("disabled",true);
            $("#decimalPoint").attr("disabled",true);
            $("#equal").attr("disabled",true);
        }
        if(operatorZeroFlag){
            $("#zero").attr("disabled",true);
            $("#one").attr("disabled",true);
            $("#two").attr("disabled",true);
            $("#three").attr("disabled",true);
            $("#four").attr("disabled",true);
            $("#Five").attr("disabled",true);
            $("#Six").attr("disabled",true);
            $("#Seven").attr("disabled",true);
            $("#Eight").attr("disabled",true);
            $("#Nine").attr("disabled",true);
        }
        $("h1").text(value);
    });

    $("#decimalPoint").click(function(){
        decimalPointFlag=false;
        operatorZeroFlag=false;
        value+=$(this).html();
        $("#zero").attr("disabled",false);
        $("#doubleZero").attr("disabled",false);
        $("#one").attr("disabled",false);
        $("#two").attr("disabled",false);
        $("#three").attr("disabled",false);
        $("#four").attr("disabled",false);
        $("#Five").attr("disabled",false);
        $("#Six").attr("disabled",false);
        $("#Seven").attr("disabled",false);
        $("#Eight").attr("disabled",false);
        $("#Nine").attr("disabled",false);
        $("#plus").attr("disabled",true);
        $("#minus").attr("disabled",true);
        $("#multiply").attr("disabled",true);
        $("#divide").attr("disabled",true);
        $("#decimalPoint").attr("disabled",true);
        $("#equal").attr("disabled",true);
        $("h1").text(value);
    });
    
    $("#AC").click(function(){
        value=0;
        decimalPointFlag=true;
        CalculationFlag=false;
        operatorZeroFlag=false;
        equalFlag=true;
        $("#zero").attr("disabled",true);
        $("#doubleZero").attr("disabled",true);
        $("#one").attr("disabled",false);
        $("#two").attr("disabled",false);
        $("#three").attr("disabled",false);
        $("#four").attr("disabled",false);
        $("#Five").attr("disabled",false);
        $("#Six").attr("disabled",false);
        $("#Seven").attr("disabled",false);
        $("#Eight").attr("disabled",false);
        $("#Nine").attr("disabled",false);
        $("#plus").attr("disabled",true);
        $("#minus").attr("disabled",false);
        $("#multiply").attr("disabled",true);
        $("#divide").attr("disabled",true);
        $("#decimalPoint").attr("disabled",false);
        $("#equal").attr("disabled",true);
        $("h1").text(value);
    });

    $("#equal").click(function(){
        value=safeEval(value);
        equalFlag=false;
        operatorZeroFlag=false;
        if(value=="0"){
            $("#multiply").attr("disabled",true);
            $("#divide").attr("disabled",true);
        }else{
            $("#multiply").attr("disabled",false);
            $("#divide").attr("disabled",false);
        }
        $("#plus").attr("disabled",false);
        $("#minus").attr("disabled",false);
        $("#decimalPoint").attr("disabled",true);
        $("#equal").attr("disabled",true);
        $("#zero").attr("disabled",true);
        $("#doubleZero").attr("disabled",true);
        $("#one").attr("disabled",true);
        $("#two").attr("disabled",true);
        $("#three").attr("disabled",true);
        $("#four").attr("disabled",true);
        $("#Five").attr("disabled",true);
        $("#Six").attr("disabled",true);
        $("#Seven").attr("disabled",true);
        $("#Eight").attr("disabled",true);
        $("#Nine").attr("disabled",true);
        $("h1").text(value);
    });
});